### ISSUE TITLE
no hdf5 file

### ISSUE THREAD

**Issue by sqschrispaul** [bkasvenkatesh/Classifying-Environmental-Sounds-with-Image-Networks#1]
can you give the hdf5 file

**Comment by bkasvenkatesh** [comment]
Hello Chris,

HDF5 file is essentially a database and in my case, it is over 50 GB in size.
You could create it on your own through the Nvidia DIGITS application, if you have the pictures dataset in JPEG or PNG, etc sorted in folders class-wise.
